[profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth_rpc_url = 'https://eth-sepolia.g.alchemy.com/v2/ZiYanrFQbMUEnpUyeXkc8z3taBV1avKW'
etherscan_api_key = 'YW47MUC27VI263X74CVFUNHQA8VKIUHAPP'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# solc_version = "0.6.12"
